
// This script runs after jsDoc runs, and it adds MathJax support to all pages
// generated by jsDoc.

import path from 'node:path'
import url from 'node:url'
import fs from 'node:fs'

console.log( 'Adding MathJax header to all jsDoc-generated files...' )

// the header to add:
const mathjaxHeader = `
<script>
    MathJax = { tex: { inlineMath: [['$', '$'], ['\\\\(', '\\\\)']] } };
</script>
<script id="MathJax-script" async
        src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js">
</script>
`

// find the target directory
const docsFolder = path.join(
    path.dirname( url.fileURLToPath( import.meta.url ) ),
    '../docs'
)

// loop through all HTML files in it
let numDone = 0
fs.readdirSync( docsFolder ).forEach( ( filename ) => {
    if ( filename.endsWith( '.html' ) ) {
        // read the file and append the MathJax header to its <head> element
        const contents = String(
            fs.readFileSync( path.join( docsFolder, filename ) )
        ).replace( /<\/head>/, () => mathjaxHeader + '</head>' )
        // write the file back out again, over the original
        fs.writeFileSync( path.join( docsFolder, filename ), contents )
        numDone++
    }
} )

console.log( `Done (${numDone} files changed).` )
